apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-api
  template:
    metadata:
      labels:
        app: dotnet-api
    spec:
      containers:
        - name: dotnet-api
          image: sakshiacr25.azurecr.io/api:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-api-service
spec:
  type: LoadBalancer
  selector:
    app: dotnet-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
